services:
  database:
    image: postgres
    ports:
      - 5432:5432
    restart: always

    environment:
      POSTGRES_USER: hp_admin
      POSTGRES_PASSWORD: Nudelholz03#
      POSTGRES_DB: hp_postgres

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080